name: supabase-db-diff
on: { workflow_dispatch: {} }
permissions:
  contents: write
  pull-requests: write
env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10 }

      # Non-interactive login + link to project (uses API, not DB TCP)
      - name: Supabase login
        run: pnpm dlx supabase@latest login --token "${SUPABASE_ACCESS_TOKEN}"

      - name: Link project
        run: pnpm dlx supabase@latest link --project-ref "${SUPABASE_PROJECT_REF}"

      # Diff uses Docker (available on GitHub runners) + API, no direct DB URL
      - name: Create migration diff
        run: |
          STAMP=$(date -u +%Y%m%d%H%M%S)
          pnpm dlx supabase@latest db diff \
            --linked \
            --schema public \
            -f "supabase/migrations/${STAMP}_auto.sql" || true

      # Typegen via API (no DB URL, no TCP)
      - name: Generate TypeScript DB types
        run: |
          mkdir -p src/lib
          pnpm dlx supabase@latest gen types typescript \
            --project-id "${SUPABASE_PROJECT_REF}" \
            -s public -s auth -s storage > src/lib/database.types.ts

      - name: Create PR if changed
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(db): auto diff + typegen"
          title: "chore(db): auto diff + typegen"
          branch: chore/db-diff
          add-paths: |
            supabase/migrations/**
            src/lib/database.types.ts