name: supabase-db-auto
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

env:
  SUPABASE_DB_URL:       ${{ secrets.SUPABASE_DB_URL }}
  SUPABASE_PROJECT_REF:  ${{ secrets.SUPABASE_PROJECT_REF }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

jobs:
  auto_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bail if last commit from Actions bot
        run: |
          if git log -1 --pretty=%an | grep -qi "github-actions"; then
            echo "Last commit from GitHub Actions; exiting."
            exit 0
          fi

      - uses: pnpm/action-setup@v4

      - name: Validate secrets
        run: |
          set -euo pipefail
          test -n "${SUPABASE_DB_URL}" || { echo "ERR: SUPABASE_DB_URL missing"; exit 1; }
          test -n "${SUPABASE_ACCESS_TOKEN}" || { echo "ERR: SUPABASE_ACCESS_TOKEN missing"; exit 1; }

      - name: Install Supabase CLI globally (npm)
        run: |
          npm install -g supabase
          supabase --version

      - name: Supabase CLI login
        run: supabase login --token "${SUPABASE_ACCESS_TOKEN}"

      - name: Create migration diff (no Docker)
        run: |
          set -euo pipefail
          STAMP="$(date -u +%Y%m%d%H%M%S)"
          supabase db diff \
            --db-url "${SUPABASE_DB_URL}" \
            --schema public \
            --use-pg-schema \
            -f "supabase/migrations/${STAMP}_auto.sql" || true

      - name: Apply migrations (db push)
        run: supabase db push --db-url "${SUPABASE_DB_URL}" --yes --include-all

      - name: Regenerate TypeScript DB types (via DB URL)
        run: |
          set -euo pipefail
          mkdir -p src/lib
          supabase gen types typescript \
            --db-url "${SUPABASE_DB_URL}" \
            -s public -s auth -s storage > src/lib/database.types.ts
          head -n 3 src/lib/database.types.ts || true

      - name: Commit and push changes to main
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add supabase/migrations/** src/lib/database.types.ts || true
          git diff --cached --quiet && { echo "No changes"; exit 0; }
          git commit -m "chore(db): diff+push+typegen [skip ci]"
          git push origin main