name: supabase-db-auto
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

env:
  SUPABASE_DB_URL:       ${{ secrets.SUPABASE_DB_URL }}       # session pooler URL with password
  SUPABASE_PROJECT_ID:   ${{ secrets.SUPABASE_PROJECT_ID }}   # UUID (not ref)
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }} # sbp_ token

jobs:
  auto_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # prevent infinite loop if last commit came from this workflow
      - name: Bail if last commit from Actions bot
        run: |
          if git log -1 --pretty=%an | grep -qi "github-actions"; then
            echo "Last commit from GitHub Actions; exiting."
            exit 0
          fi

      - uses: pnpm/action-setup@v4
        with: { version: 10 }

      - name: Validate secrets
        run: |
          test -n "${SUPABASE_DB_URL}"
          test -n "${SUPABASE_PROJECT_ID}"
          test -n "${SUPABASE_ACCESS_TOKEN}"

      - name: Login Supabase CLI
        run: pnpm dlx supabase@latest login --token "${SUPABASE_ACCESS_TOKEN}"

      # Optional: create diff migration from remote to repo (non-fatal if no changes)
      - name: Create migration diff
        run: |
          STAMP="$(date -u +%Y%m%d%H%M%S)"
          pnpm dlx supabase@latest db diff \
            --db-url "${SUPABASE_DB_URL}" \
            --schema public \
            -f "supabase/migrations/${STAMP}_auto.sql" || true

      - name: Apply migrations (db push)
        run: pnpm dlx supabase@latest db push --db-url "${SUPABASE_DB_URL}" --yes

      - name: Regenerate TypeScript DB types
        run: |
          mkdir -p src/lib
          pnpm dlx supabase@latest gen types typescript \
            --project-id "${SUPABASE_PROJECT_ID}" \
            -s public -s auth -s storage > src/lib/database.types.ts
          head -n 3 src/lib/database.types.ts

      - name: Commit and push changes to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add supabase/migrations/** src/lib/database.types.ts
          git diff --cached --quiet && { echo "No changes"; exit 0; }
          git commit -m "chore(db): diff+push+typegen [skip ci]"
          git push origin main