name: supabase-db-auto

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "supabase/**"
      - "src/**"
      - "scripts/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/supabase-db-auto.yml"

permissions:
  contents: write

env:
  SUPABASE_DB_URL:       ${{ secrets.SUPABASE_DB_URL }}
  SUPABASE_PROJECT_REF:  ${{ secrets.SUPABASE_PROJECT_REF }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

jobs:
  # ------------------ Types on push (no DB writes) ------------------
  types_only:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bail if last commit from Actions bot
        run: |
          if git log -1 --pretty=%an | grep -qi "github-actions"; then
            echo "Last commit from GitHub Actions; exiting."
            exit 0
          fi

      - name: Supabase CLI (npx) – version
        run: npx supabase@latest --version

      - name: Login to Supabase
        run: npx supabase@latest login --token "${SUPABASE_ACCESS_TOKEN}"

      - name: Generate TypeScript types (DB URL)
        run: |
          set -euo pipefail
          mkdir -p src/lib
          npx supabase@latest gen types typescript \
            --db-url "${SUPABASE_DB_URL}" \
            -s public -s auth -s storage > src/lib/database.types.ts
          head -n 3 src/lib/database.types.ts || true

      - name: Commit & push types (if changed)
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/lib/database.types.ts
          git diff --cached --quiet && { echo "No type changes"; exit 0; }
          git commit -m "chore(types): regenerate DB types [skip ci]"
          git push origin main

  # ------------------ Full DB ops (manual only) ------------------
  db_ops:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate secrets
        run: |
          set -euo pipefail
          test -n "${SUPABASE_DB_URL}" || { echo "ERR: SUPABASE_DB_URL missing"; exit 1; }
          test -n "${SUPABASE_ACCESS_TOKEN}" || { echo "ERR: SUPABASE_ACCESS_TOKEN missing"; exit 1; }

      - name: Supabase CLI (npx) – version
        run: npx supabase@latest --version

      - name: Login to Supabase
        run: npx supabase@latest login --token "${SUPABASE_ACCESS_TOKEN}"

      - name: Create migration diff (no Docker required)
        run: |
          set -euo pipefail
          STAMP="$(date -u +%Y%m%d%H%M%S)"
          mkdir -p supabase/migrations
          npx supabase@latest db diff \
            --db-url "${SUPABASE_DB_URL}" \
            --schema public \
            --use-pg-schema \
            -f "supabase/migrations/${STAMP}_auto.sql" || true

      - name: Apply migrations (db push)
        run: npx supabase@latest db push --db-url "${SUPABASE_DB_URL}" --yes --include-all

      - name: Regenerate TypeScript types
        run: |
          set -euo pipefail
          mkdir -p src/lib
          npx supabase@latest gen types typescript \
            --db-url "${SUPABASE_DB_URL}" \
            -s public -s auth -s storage > src/lib/database.types.ts

      - name: Commit & push migrations/types (if changed)
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add supabase/migrations/** src/lib/database.types.ts || true
          git diff --cached --quiet && { echo "No changes"; exit 0; }
          git commit -m "chore(db): diff+push+typegen [skip ci]"
          git push origin main